
#========================================MYSQL================================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false&characterEncoding=utf8
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
